version: '3.9'

volumes: # named volumes can be managed easier using docker-compose
  mysql-volume:
  postgres-volume:
  kamailio-volume:

networks:
  bridge-network:
    driver: bridge
  host-network:
    driver: host
  macvlan-network:
    driver: macvlan

#configs:
#  kamailio_conf:
#    file: ./config/sip/kamailio/Kamailio.cfg
#  postgres_env:
#    file: config/db/postgres/Postgres.env # configure postgres



services:
  ######################## MySQL ###########################
  mysql-service:
    image: "mysql:8.0.32-oracle"
    container_name: "mysql-container"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - mysql/MySQL.env # See all the environment variables
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql # persist data even if container shuts down
    networks:
      - bridge-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
  ######################## Kamailio ###########################
  kamailio: #https://www.slideshare.net/pvisintin/kamailio-with-docker-and-kubernetes
#    image: "kamailio:5.5.6-bullseye"
    container_name: "kamailio-container"
#    command:
#      - kamdbctl create
    build:
      context: .
      dockerfile: docker/Kamailio.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - kamailio/Kamailio.env
    ports:
      - "5060:5060"
      - "5060:5060/udp"
    volumes:
#      - type: bind
#        source: "./config/sip/kamailio/Kamctlrc"
#        target: "/etc/kamailio/kamctlrc"
      - type: bind
        source: "./kamailio/Kamailio.cfg"
        target: "/etc/kamailio/kamailio.cfg"
        consistency: consistent

    networks:
      - host-network



